apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-deployer
  namespace: default
secrets:
- name: svc-deployer-token  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: svc-deployer-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- namespace: default
  kind: ServiceAccount
  name: svc-deployer
---
apiVersion: v1
kind: Secret
metadata:
  name: svc-deployer-token
  annotations:
    kubernetes.io/service-account.name: svc-deployer
type: kubernetes.io/service-account-token 